// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGNw2WhtwRHIAxDtbfQtzysY0cVIOKCU',
    appId: '1:282400277502:web:f44be6bd9eded9543736af',
    messagingSenderId: '282400277502',
    projectId: 'healing-hand-personal',
    authDomain: 'healing-hand-personal.firebaseapp.com',
    storageBucket: 'healing-hand-personal.appspot.com',
    measurementId: 'G-508CK7JG72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWaOoFzd7K-mb5P5NMcmT0Ucso2ce2yy0',
    appId: '1:282400277502:android:d84369781eb81fd53736af',
    messagingSenderId: '282400277502',
    projectId: 'healing-hand-personal',
    storageBucket: 'healing-hand-personal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdy1YknefoGCPDb3E5t6LO0UyHRiJZdWg',
    appId: '1:282400277502:ios:54f39e8a71465c5d3736af',
    messagingSenderId: '282400277502',
    projectId: 'healing-hand-personal',
    storageBucket: 'healing-hand-personal.appspot.com',
    iosBundleId: 'com.example.healingHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdy1YknefoGCPDb3E5t6LO0UyHRiJZdWg',
    appId: '1:282400277502:ios:3066d7582820f4623736af',
    messagingSenderId: '282400277502',
    projectId: 'healing-hand-personal',
    storageBucket: 'healing-hand-personal.appspot.com',
    iosBundleId: 'com.example.healingHand.RunnerTests',
  );
}
