// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4vpuchFxuatNTp6GpACD0SlIp3a8pR4',
    appId: '1:945013281355:web:43eba57ff417264c28f3ce',
    messagingSenderId: '945013281355',
    projectId: 'healing-hand-37032',
    authDomain: 'healing-hand-37032.firebaseapp.com',
    storageBucket: 'healing-hand-37032.appspot.com',
    measurementId: 'G-JYZ0PGWJZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMclRuS-mxUs7bXB9kAwQitMnD46GOB_0',
    appId: '1:945013281355:android:b09b67e9300897dd28f3ce',
    messagingSenderId: '945013281355',
    projectId: 'healing-hand-37032',
    storageBucket: 'healing-hand-37032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7Nsp5qT5kPlTc5BWH0mzhkNiCixADGw',
    appId: '1:945013281355:ios:85f7ffebc8ec490228f3ce',
    messagingSenderId: '945013281355',
    projectId: 'healing-hand-37032',
    storageBucket: 'healing-hand-37032.appspot.com',
    iosBundleId: 'com.example.healingHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7Nsp5qT5kPlTc5BWH0mzhkNiCixADGw',
    appId: '1:945013281355:ios:d98b494794a596d828f3ce',
    messagingSenderId: '945013281355',
    projectId: 'healing-hand-37032',
    storageBucket: 'healing-hand-37032.appspot.com',
    iosBundleId: 'com.example.healingHand.RunnerTests',
  );
}
